services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: gym_user
      POSTGRES_PASSWORD: gym_pass
      POSTGRES_DB: gym_db
    ports:
      - "5432:5432"
    volumes:
      - gym_pg_data:/var/lib/postgresql/data

volumes:
  gym_pg_data:
