"""agregar external_id a payments

Revision ID: fb6e950a17b7
Revises: bcaa5ca1808f
Create Date: 2026-08-13 21:44:57.585921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6e950a17b7'
down_revision: Union[str, None] = 'bcaa5ca1808f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('external_id', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'payments', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'external_id')
    # ### end Alembic commands ###
